import { 
  WidgetDefinition, 
  IButtonWidget, 
  ITextWidget, 
  IInputWidget, 
  IImageWidget, 
  ICardWidget,
  IDividerWidget,
  ISpacerWidget,
  IIconWidget,
  IBadgeWidget,
  IAvatarWidget,
  IProgressWidget,
  ICheckboxWidget,
  IRadioWidget,
  ISelectWidget,
  ITextareaWidget,
  ISliderWidget,
  ISwitchWidget,
  ITabsWidget,
  IAccordionWidget,
  IContainerWidget
} from '../types';

export const widgetDefinitions: WidgetDefinition[] = [
  {
    type: 'container',
    name: 'Контейнер',
    description: 'Контейнер для размещения и выравнивания других элементов',
    icon: 'Package',
    category: 'layout',
    defaultProps: {
      alignment: 'top-left',
      direction: 'column',
      wrap: false,
      gap: 8,
      children: [],
      alpha: 100,
      rotation: 0,
      padding: 16,
      margin: 0,
      backgroundColor: 'rgba(240, 240, 240, 0.3)',
      scrollMode: 'none',
      clipContent: false,
      widthMode: 'fill',
      heightMode: 'fixed',
      heightValue: 200,
    },
    defaultStyle: {
      backgroundColor: 'rgba(240, 240, 240, 0.3)',
      border: '1px dashed hsl(0 0% 80%)',
      borderRadius: 8,
      padding: '16px',
    },
    defaultSize: { width: 300, height: 200 },
  },
  {
    type: 'button',
    name: 'Кнопка',
    description: 'Интерактивная кнопка для действий пользователя',
    icon: 'MousePointer',
    category: 'basic',
    defaultProps: {
      text: 'Нажмите здесь',
      variant: 'primary' as const,
      disabled: false,
    },
    defaultStyle: {
      backgroundColor: 'hsl(142 100% 31%)',
      color: 'white',
      fontSize: 14,
      fontWeight: '500',
      borderRadius: 8,
      padding: '12px 24px',
    },
    defaultSize: { width: 140, height: 44 },
  },
  {
    type: 'text',
    name: 'Текст',
    description: 'Текстовый блок для заголовков и содержимого',
    icon: 'Type',
    category: 'basic',
    defaultProps: {
      content: 'Ваш текст здесь',
      align: 'left' as const,
      tag: 'p' as const,
    },
    defaultStyle: {
      color: 'hsl(0 0% 10%)',
      fontSize: 16,
      fontWeight: '400',
    },
    defaultSize: { width: 200, height: 24 },
  },
  {
    type: 'input',
    name: 'Поле ввода',
    description: 'Поле для ввода данных пользователем',
    icon: 'Edit3',
    category: 'form',
    defaultProps: {
      placeholder: 'Введите значение...',
      inputType: 'text' as const,
      required: false,
      disabled: false,
    },
    defaultStyle: {
      backgroundColor: 'white',
      color: 'hsl(0 0% 10%)',
      fontSize: 14,
      border: '1px solid hsl(0 0% 90%)',
      borderRadius: 8,
      padding: '12px 16px',
    },
    defaultSize: { width: 200, height: 44 },
  },
  {
    type: 'image',
    name: 'Изображение',
    description: 'Картинка или медиа контент',
    icon: 'Image',
    category: 'media',
    defaultProps: {
      src: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=300&fit=crop',
      alt: 'Изображение',
      objectFit: 'cover' as const,
    },
    defaultStyle: {
      borderRadius: 8,
    },
    defaultSize: { width: 200, height: 150 },
  },
  {
    type: 'card',
    name: 'Карточка',
    description: 'Универсальная карточка контента',
    icon: 'Layout',
    category: 'layout',
    defaultProps: {
      title: 'Заголовок карточки',
      content: 'Описание или содержимое карточки',
      hasFooter: false,
    },
    defaultStyle: {
      backgroundColor: 'white',
      borderRadius: 12,
      padding: '20px',
      border: '1px solid hsl(0 0% 90%)',
    },
    defaultSize: { width: 280, height: 160 },
  },
  {
    type: 'divider',
    name: 'Разделитель',
    description: 'Визуальный разделитель контента',
    icon: 'Minus',
    category: 'layout',
    defaultProps: {
      orientation: 'horizontal',
      thickness: 1,
      color: 'hsl(0 0% 80%)',
    },
    defaultStyle: {},
    defaultSize: { width: 200, height: 1 },
  },
  {
    type: 'spacer',
    name: 'Отступ',
    description: 'Пустое пространство для выравнивания',
    icon: 'Space',
    category: 'layout',
    defaultProps: {
      size: 20,
    },
    defaultStyle: {
      backgroundColor: 'transparent',
    },
    defaultSize: { width: 20, height: 20 },
  },
  {
    type: 'icon',
    name: 'Иконка',
    description: 'Векторная иконка',
    icon: 'Star',
    category: 'basic',
    defaultProps: {
      name: 'star',
      size: 24,
      color: 'hsl(142 100% 31%)',
    },
    defaultStyle: {},
    defaultSize: { width: 24, height: 24 },
  },
  {
    type: 'badge',
    name: 'Значок',
    description: 'Небольшой значок с текстом',
    icon: 'Tag',
    category: 'basic',
    defaultProps: {
      text: 'Новое',
      variant: 'default',
      size: 'md',
    },
    defaultStyle: {
      backgroundColor: 'hsl(142 100% 31%)',
      color: 'white',
      borderRadius: 12,
      padding: '4px 8px',
      fontSize: 12,
    },
    defaultSize: { width: 60, height: 24 },
  },
  {
    type: 'avatar',
    name: 'Аватар',
    description: 'Круглое изображение пользователя',
    icon: 'User',
    category: 'basic',
    defaultProps: {
      alt: 'Пользователь',
      fallback: 'U',
      size: 40,
    },
    defaultStyle: {
      backgroundColor: 'hsl(142 100% 31%)',
      color: 'white',
      borderRadius: 50,
    },
    defaultSize: { width: 40, height: 40 },
  },
  {
    type: 'progress',
    name: 'Прогресс',
    description: 'Индикатор выполнения',
    icon: 'BarChart3',
    category: 'basic',
    defaultProps: {
      value: 50,
      max: 100,
      showValue: true,
      variant: 'default',
    },
    defaultStyle: {
      backgroundColor: 'hsl(0 0% 90%)',
      borderRadius: 4,
    },
    defaultSize: { width: 200, height: 8 },
  },
  {
    type: 'checkbox',
    name: 'Чекбокс',
    description: 'Флажок для выбора',
    icon: 'CheckSquare',
    category: 'form',
    defaultProps: {
      label: 'Опция',
      checked: false,
      disabled: false,
    },
    defaultStyle: {},
    defaultSize: { width: 120, height: 20 },
  },
  {
    type: 'radio',
    name: 'Радиокнопка',
    description: 'Переключатель для выбора одной опции',
    icon: 'Circle',
    category: 'form',
    defaultProps: {
      label: 'Опция',
      checked: false,
      disabled: false,
      name: 'radio-group',
    },
    defaultStyle: {},
    defaultSize: { width: 120, height: 20 },
  },
  {
    type: 'select',
    name: 'Выпадающий список',
    description: 'Список для выбора значения',
    icon: 'ChevronDown',
    category: 'form',
    defaultProps: {
      placeholder: 'Выберите значение',
      options: ['Опция 1', 'Опция 2', 'Опция 3'],
      disabled: false,
    },
    defaultStyle: {
      backgroundColor: 'white',
      border: '1px solid hsl(0 0% 90%)',
      borderRadius: 8,
      padding: '8px 12px',
    },
    defaultSize: { width: 200, height: 40 },
  },
  {
    type: 'textarea',
    name: 'Текстовая область',
    description: 'Многострочное поле ввода',
    icon: 'AlignLeft',
    category: 'form',
    defaultProps: {
      placeholder: 'Введите текст...',
      rows: 3,
      disabled: false,
      resize: 'vertical',
    },
    defaultStyle: {
      backgroundColor: 'white',
      border: '1px solid hsl(0 0% 90%)',
      borderRadius: 8,
      padding: '8px 12px',
    },
    defaultSize: { width: 200, height: 80 },
  },
  {
    type: 'slider',
    name: 'Слайдер',
    description: 'Ползунок для выбора числового значения',
    icon: 'Sliders',
    category: 'form',
    defaultProps: {
      min: 0,
      max: 100,
      step: 1,
      value: 50,
      disabled: false,
    },
    defaultStyle: {},
    defaultSize: { width: 200, height: 20 },
  },
  {
    type: 'switch',
    name: 'Переключатель',
    description: 'Переключатель вкл/выкл',
    icon: 'ToggleLeft',
    category: 'form',
    defaultProps: {
      label: 'Включить',
      checked: false,
      disabled: false,
    },
    defaultStyle: {},
    defaultSize: { width: 120, height: 20 },
  },
  {
    type: 'tabs',
    name: 'Вкладки',
    description: 'Навигация по вкладкам',
    icon: 'Tabs',
    category: 'layout',
    defaultProps: {
      tabs: [
        { id: 'tab1', label: 'Вкладка 1', content: 'Содержимое 1' },
        { id: 'tab2', label: 'Вкладка 2', content: 'Содержимое 2' },
      ],
      activeTab: 'tab1',
    },
    defaultStyle: {
      backgroundColor: 'white',
      border: '1px solid hsl(0 0% 90%)',
      borderRadius: 8,
    },
    defaultSize: { width: 300, height: 200 },
  },
  {
    type: 'accordion',
    name: 'Аккордеон',
    description: 'Сворачиваемые секции контента',
    icon: 'ChevronDown',
    category: 'layout',
    defaultProps: {
      items: [
        { id: 'item1', title: 'Секция 1', content: 'Содержимое секции 1', open: false },
        { id: 'item2', title: 'Секция 2', content: 'Содержимое секции 2', open: false },
      ],
      type: 'single',
    },
    defaultStyle: {
      backgroundColor: 'white',
      border: '1px solid hsl(0 0% 90%)',
      borderRadius: 8,
    },
    defaultSize: { width: 300, height: 150 },
  },
];

export function createDefaultWidget(type: string, position: { x: number; y: number }): any {
  const definition = widgetDefinitions.find(def => def.type === type);
  if (!definition) return null;

  const baseWidget = {
    id: `widget_${type}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    type: definition.type,
    position,
    size: definition.defaultSize,
    zIndex: 1,
    style: definition.defaultStyle,
    props: definition.defaultProps,
    zone: undefined,
  };

  return baseWidget;
}